### ISSUE TITLE
Uncaught The "data" argument must be one of type string, TypedArray, or DataView. hash.js

### ISSUE THREAD

**Issue by wmehilos** [dldl/sphinx-preview#18]
[Enter steps to reproduce:]

1. open index.rst
2. Hit control + opt + O to open a preview. 

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [sphinx-preview](https://github.com/dldl/sphinx-preview) package 0.1.5

### Stack Trace

Uncaught The "data" argument must be one of type string, TypedArray, or DataView. Received type object

```
At internal/crypto/hash.js:58

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type object
    at Hash.update (internal/crypto/hash.js:58:11)
    at Object.getContainerName (/packages/sphinx-preview/lib/sphinx-preview.js:71:24)
    at Object.startSphinxServer (/packages/sphinx-preview/lib/sphinx-preview.js:115:32)
    at Object.toggle (/packages/sphinx-preview/lib/sphinx-preview.js:34:12)
    at HTMLElement.sphinxPreviewToggle (/packages/sphinx-preview/lib/sphinx-preview.js:23:47)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347598)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718718)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:726641)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
  2x -7:26.4.0 sphinx-preview:toggle (input.hidden-input)
     -4:29.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:05.2.0 sphinx-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-rst-preview-docutils 1.0.0 
browser-plus 0.0.98 
hex-view 0.2.1 
language-restructuredtext 1.1.2 
sphinx-preview 0.1.5 
```

**Comment by wmehilos** [comment]
same issue happens on windows 10 1903 by the way
